import React from "react";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./css/globals.css";
import { ThemeModeScript, ThemeProvider } from 'flowbite-react';
import customTheme from "@/utils/theme/custom-theme";
import { Toaster } from "react-hot-toast"


const plus_jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.APP_URL
      ? `${process.env.APP_URL}`
      : process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_URL}`
      : `http://localhost:${process.env.PORT || 3000}`
  ),
  title: "OneLink Marketing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        {typeof window !== "undefined" && <ThemeModeScript />}
        <link
          href="https://fonts.googleapis.com/css2?family=Archivo+Expanded:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${plus_jakarta_sans.className}`}>
        <ThemeProvider theme={customTheme}>
          {children}
          <Toaster position="top-center" reverseOrder={false} />
        </ThemeProvider>
      </body>
    </html>

  );
}
